service: retail-analytics
runtime: python310

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  ADMIN_PIN: "4321"
  SUPABASE_DB_URL: "postgresql://postgres:%23Kenya%402025@db.jojtpfepksshdzpxjlvf.supabase.co:5432/postgres?sslmode=require"

instance_class: F1  # Small instance (low-cost)

automatic_scaling:
  min_instances: 1
  max_instances: 2
